version: !!str 3

services:
  nginx:
    image: nginx:1.21
    restart: unless-stopped
    ports:
      - "8080:80"
      - "8090:443"
    volumes:
      - /var/opt/nginx/data:/usr/share/nginx/html
      - /var/opt/nginx/config/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - nginx_2

networks:
  nginx_2:
    external: true
